ALL:
	gcc rfcomm-client.c -o rfcomm-client -lbluetooth -lproto -L.
	gcc rfcomm-server.c -o rfcomm-server -lbluetooth -lproto -L.
	gcc l2cap-client.c -o l2cap-client -lbluetooth -lproto -L.
	gcc l2cap-server.c -o l2cap-server -lbluetooth -lproto -L.

